module "vpc" {
    source = "./module"
    cidr_block = "10.0.0.0/16"
    vpc_name                    = "ibm_vpc"
    vpc_id                      = "ibm_vpc"
    public_subnet_cidr_block    = "10.0.0.0/20"
    private_subnet_cidr_block   = "10.0.32.0/20"
    app_subnet_cidr_block       = "10.0.16.0/20"
    public_availability_zone    = "us-east-1a"
    private_availability_zone   = "us-east-1b"
    public_subnet_name          = "ibm_public_sn"
    private_subnet_name         = "ibm_private_sn"
    app_subnet_name             =  "ibm_app_sn"
    igw_name                    = "ibm_igw"
    eip_name                    = "ibm_eip"
    nat_gw_name                 = "ibm_nat_gw"
    public_rt_name              = "ibm_public_rt"
    private_rt_name             = "ibm_private_rt"
    app_rt_name                 =  "ibm_app_rt"
    public_nacl_name            = "ibm_public_nacl"
    private_nacl_name           = "ibm_private_nacl"
    app_nacl_name               = "ibm_app_nacl"
}

  
